// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQd1pkmE2bV92nd2uXhfgPwZTgJY8iSA',
    appId: '1:950638541761:android:8bacf40de67277c3fccd40',
    messagingSenderId: '950638541761',
    projectId: 'traintastic-2e43d',
    storageBucket: 'traintastic-2e43d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxI8IWfQfZF6j31oy8gPqYXaRSQHIXP2E',
    appId: '1:950638541761:ios:b4316a069a262209fccd40',
    messagingSenderId: '950638541761',
    projectId: 'traintastic-2e43d',
    storageBucket: 'traintastic-2e43d.firebasestorage.app',
    iosBundleId: 'com.example.traintastic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxI8IWfQfZF6j31oy8gPqYXaRSQHIXP2E',
    appId: '1:950638541761:ios:b4316a069a262209fccd40',
    messagingSenderId: '950638541761',
    projectId: 'traintastic-2e43d',
    storageBucket: 'traintastic-2e43d.firebasestorage.app',
    iosBundleId: 'com.example.traintastic',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyKZbi9Q156YgGsVZTOyxmxb-hCDyMO8',
    appId: '1:950638541761:web:a67b2e54f9b9abd5fccd40',
    messagingSenderId: '950638541761',
    projectId: 'traintastic-2e43d',
    authDomain: 'traintastic-2e43d.firebaseapp.com',
    storageBucket: 'traintastic-2e43d.firebasestorage.app',
    measurementId: 'G-FL4150H503',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLyKZbi9Q156YgGsVZTOyxmxb-hCDyMO8',
    appId: '1:950638541761:web:de5f4c890a038057fccd40',
    messagingSenderId: '950638541761',
    projectId: 'traintastic-2e43d',
    authDomain: 'traintastic-2e43d.firebaseapp.com',
    storageBucket: 'traintastic-2e43d.firebasestorage.app',
    measurementId: 'G-121ZYF2YKJ',
  );

}